version: '3'

services:
  nginx:
    image: nginx:1.13
    restart: always
    container_name: nginx
    volumes: 
      - /Users/docker/nginx/docker-nginx-server/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"

