version: '3'

services:
  centos:
    container_name: centos
    restart: always
    build: Dockerfile
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"

