version: '3'

services:
  centos:
    container_name: centos
    restart: always
    expose:
      - "5000"
    build:
      context: ./
      dockerfile: ./Dockerfile
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - "centos:centos"
