version: '3'

services:
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./www:/var/www
