version: '3'

services:
  nginx:
    image: nginx:1.13
    restart: always
    container_name: nginx
    volumes: 
      - /Users/docker/nginx/docker-nginx-server/logs:/var/log/nginx
      - /Users/docker/nginx/docker-nginx-server/nginx.pid:/var/run/nginx.pid
      - /Users/docker/nginx/docker-nginx-server/www:/var/www/html/public/
      - /Users/docker/nginx/docker-nginx-server/conf:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"

